# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

implicitScheme <- function(strike, maturity, type, spot, r, q, v, res, american = TRUE) {
    .Call(`_optionpricing_implicitScheme`, strike, maturity, type, spot, r, q, v, res, american)
}

#' Price options via Black-Scholes PDE
#' @param strike the strike price of the option contract
#' @param maturity the time until maturity
#' @param type either "put" or "call
#' @param spot the spot price
#' @param r the risk free rate
#' @param q the continuous dividend yield
#' @param v the volatiltiy
#' @param res the grid resolution
#' @param american bool for american options
#'
#' @description {Compute European/American options via a finite difference solver for the
#' Black-Scholes PDE.}
#' @return numeric
#' @export blackScholesPDE
blackScholesPDE <- function(strike, maturity, type, spot, r, q, v, res, american = TRUE) {
    .Call(`_optionpricing_blackScholesPDE`, strike, maturity, type, spot, r, q, v, res, american)
}

cpoisScheme <- function(strike, maturity, type, spot, r, a, b, res, american = TRUE) {
    .Call(`_optionpricing_cpoisScheme`, strike, maturity, type, spot, r, a, b, res, american)
}

#' Price options via Compensated Poisson PDE
#' @param strike the strike price of the option contract
#' @param maturity the time until maturity
#' @param type either "put" or "call
#' @param spot the spot price
#' @param r the risk free rate
#' @param a coefficient of the Poisson process
#' @param b coefficient of the compensating drift
#' @param res the grid resolution
#' @param american bool for american options
#'
#' @description {Compute European/American options via a finite difference solver for the
#' PDE for compensated Poisson log-returns.}
#' @return numeric
#' @export cpoisPDE
cpoisPDE <- function(strike, maturity, type, spot, r, a, b, res, american = TRUE) {
    .Call(`_optionpricing_cpoisPDE`, strike, maturity, type, spot, r, a, b, res, american)
}

imexScheme <- function(strike, maturity, type, spot, r, q, v, lambda, jumpDistr, jumpParam, res, american = TRUE) {
    .Call(`_optionpricing_imexScheme`, strike, maturity, type, spot, r, q, v, lambda, jumpDistr, jumpParam, res, american)
}

#' Price options via Black-Scholes PDE
#' @param strike the strike price of the option contract
#' @param maturity the time until maturity
#' @param type either "put" or "call"
#' @param spot the spot price
#' @param r the risk free rate
#' @param q the continuous dividend yield
#' @param v the volatiltiy
#' @param lambda the mean number of jumps annually
#' @param jumpDistr name of jump-size distribution: "norm", "kou" or "dkou"
#' @param jumpParam vector of jump parameters, see details
#' @param res the time-space resolution
#' @param american bool for american options
#'
#' @description {Compute European/American options via a finite difference solver for the
#' jump diffusion PIDE.}
#' @return numeric
#' @export pricerPIDE
pricerPIDE <- function(strike, maturity, type, spot, r, q, v, lambda, jumpDistr, jumpParam, res, american = TRUE) {
    .Call(`_optionpricing_pricerPIDE`, strike, maturity, type, spot, r, q, v, lambda, jumpDistr, jumpParam, res, american)
}

